<a href="https://colab.research.google.com/github/Devsoni-designer/Air-Balloon-Ride/blob/main/C_124_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
A = [2, -5, 8, 0]
print(A)

B = [[1, -8], [12, 2]]
print(B)

[2, -5, 8, 0]
[[1, -8], [12, 2]]


In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)
print(type(arr))


[1 2 3 4]
<class 'numpy.ndarray'>


In [4]:
arr_2d = np.array([[1,2,3], ['a', 'z', 5], [True, -10, 'v']])
print(arr_2d)
print(type(arr_2d))

[['1' '2' '3']
 ['a' 'z' '5']
 ['True' '-10' 'v']]
<class 'numpy.ndarray'>


In [5]:
print(A)
print(A[3])
print(arr)
print(arr[2])

[2, -5, 8, 0]
0
[1 2 3 4]
3


In [7]:
print(arr_2d)
print(arr_2d[1,2])
print(arr_2d[2][1])

[['1' '2' '3']
 ['a' 'z' '5']
 ['True' '-10' 'v']]
5
-10


In [8]:
#Updating index no in array

arr_2d[1][0] = 10

arr_2d[2][0] = 5

print(arr_2d)

[['1' '2' '3']
 ['10' 'z' '5']
 ['5' '-10' 'v']]


In [10]:
# Mathematical Operations

#Addition
a = np.array([[1,3],
              [5,8]])

b = np.array([[-1,6],
              [2,8]])

rows = 2
cols =2

#For holding Result
c=[[0,0],
    [0,0]]

for i in range(rows):
  for j in range(cols):
    c[i][j] = a[i][j] + b[i][j]

print(a, '\n')
print(b, '\n')
print(c)


[[1 3]
 [5 8]] 

[[-1  6]
 [ 2  8]] 

[[0, 9], [7, 16]]


In [11]:
#Subtraction
a = np.array([[5,8],
               [7,-1]
                   ])

b = np.array([[9,-8],
               [0,-7]
                   ])

rows = 2
cols = 2
c = [[0,0],
      [0,0]]

for i in range(rows):
  for j in range(cols):
    c[i][j] = a[i][j] - b[i][j]

print(a, '\n')
print(b, '\n')
print(c)


[[ 5  8]
 [ 7 -1]] 

[[ 9 -8]
 [ 0 -7]] 

[[-4, 16], [7, 6]]


In [12]:
#Multiplication

b = np.array([[1,-3],
              [2,6],
              [-3,1]])

print(b, '\n')

n=5 #scalar
mul = np.zeros([3,2])

for i in range(3):
  for j in range(2):
    mul [i][j] = n* b[i][j]

print(mul)


[[ 1 -3]
 [ 2  6]
 [-3  1]] 

[[  5. -15.]
 [ 10.  30.]
 [-15.   5.]]


In [14]:
#Multiplication of array with array

a = np.array([[2,4,-7],
               [4,-6,1],
               [1,5,-8]])

b = np.array([[-2,2,-7],
               [0,-1,1],
               [1,3,-8]])

c = np.zeros([3,2])
print(c, '\n')

rows_a = 3
cols_a = rows_b = 2
cols_b = 3

for i in range(3):
  for j in range(2):
    for k in range(3):

      c[i][j] = c[i][j] + a[i][k] * b[k][j]

for rows in c:
  print(rows)



[[0. 0.]
 [0. 0.]
 [0. 0.]] 

[-11. -21.]
[-7. 17.]
[-10. -27.]
